#ifndef CPP_COVERAGE_EXAMPLE_SUB_PROJECT_HPP
#define CPP_COVERAGE_EXAMPLE_SUB_PROJECT_HPP

#ifdef _WIN32
#define CPP_COVERAGE_EXAMPLE_CALL __cdecl
#ifdef CPP_COVERAGE_EXAMPLE_STATIC_LIB
#define CPP_COVERAGE_EXAMPLE_API
#else
#ifdef CPP_COVERAGE_EXAMPLE_EXPORTING
#define CPP_COVERAGE_EXAMPLE_API __declspec( dllexport )
#else
#define CPP_COVERAGE_EXAMPLE_API __declspec( dllimport )
#endif /* CPP_COVERAGE_EXAMPLE_EXPORTING */
#endif /* CPP_COVERAGE_EXAMPLE_STATIC_LIB */
#elif __GNUC__ >= 4
#define CPP_COVERAGE_EXAMPLE_API __attribute__((visibility("default")))
#define CPP_COVERAGE_EXAMPLE_CALL
#else
#define CPP_COVERAGE_EXAMPLE_API
#define CPP_COVERAGE_EXAMPLE_CALL
#endif /* _WIN32 */

CPP_COVERAGE_EXAMPLE_API  int
CPP_COVERAGE_EXAMPLE_CALL non_zero_if_even(int x);

#endif // CPP_COVERAGE_EXAMPLE_SUB_PROJECT_HPP